### ISSUE TITLE
Código de erro: M7121-1331-P7

### ISSUE THREAD

**Issue by xupeta** [kusti8/chromium-build#1]
I used the site article https://techwiztime.com/article/netflix-on-raspberry-pi/ and on netflix get error M7121-1331-P7 in any movie or tv series.

**Comment by kusti8** [comment]
Try rebooting a few times. This sometimes happens and I have no idea why. I haven't been able to reproduce it.

**Comment by xupeta** [comment]
Thanks, i did and now is ok.
 

Sent: Sunday, July 02, 2017 at 7:04 AM
